# Generated by Django 6.0 on 2025-12-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('FASHION', 'Fashion (Second Hand)'), ('CRAFT', 'Craft (Locally Made)')], default='FASHION', max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Public Price (USD)')),
                ('cost_usd', models.DecimalField(decimal_places=2, help_text='Visible only to Admins', max_digits=10, verbose_name='Internal Cost (USD)')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='products/', verbose_name='Main Image')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size (Fashion)')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand (Fashion)')),
                ('condition', models.CharField(blank=True, choices=[('NEW_TAG', 'New with Tags'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good Condition'), ('FAIR', 'Fair Condition')], max_length=20, null=True, verbose_name='Condition (Fashion)')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Materials (Craft)')),
                ('origin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Origin (e.g. San Francisco de Paula)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
    ]
