# Generated by Django 6.0 on 2025-12-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(default='USD', editable=False, max_length=3)),
                ('currency_to', models.CharField(default='CUP', editable=False, max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, default=300.0, help_text='Current Exchange Rate: 1 USD = X CUP', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate (USD to CUP)',
                'verbose_name_plural': 'Exchange Rate',
            },
        ),
    ]
